### ISSUE TITLE
Please publish .NET Standard compatible package

### ISSUE THREAD

**Issue by adriangodong** [kyleherzog/CodeCasing#1]
I'm trying to use this package in AWS Lambda and they only able to run .NET Core 1.0.

Please republish this package targeting netcoreapp1.0 or any minimum netstandard with NETStandard.Library pinned to 1.6.0. See https://github.com/adriangodong/githubhook/pull/46 on how you can achieve this.

**Comment by kyleherzog** [comment]
Published v2.0.0 to nuget.org today, which is now a .NET Standard library.

**Comment by adriangodong** [comment]
Thank you for the update!
